name: shartflix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  equatable: ^2.0.5
  firebase_analytics: ^11.6.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.3.10
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.0.0
  get_it: ^8.0.3
  image_picker: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.1.0
  provider: ^6.1.5

flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image: "assets/splash/shartflix_splash.png"
  color: "#000000"
  android_12:
    color: "#000000"

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/euclid-circular-a/Euclid-Circular-A-Regular.ttf
          weight: 400
        - asset: assets/fonts/euclid-circular-a/Euclid-Circular-A-Medium.ttf
          weight: 500
        - asset: assets/fonts/euclid-circular-a/Euclid-Circular-A-SemiBold.ttf
          weight: 600
